### ISSUE TITLE
 'Status' object has no attribute 'quoted_status'

### ISSUE THREAD

**Issue by Fil** [YoloSwagTeam/t2m#16]
```
Traceback (most recent call last):
  File "./t2m", line 267, in <module>
    parser.dispatch()
  File "/Users/fil/Source/mastodon/t2m/ve/lib/python3.6/site-packages/argh/helpers.py", line 55, in dispatch
    return dispatch(self, *args, **kwargs)
  File "/Users/fil/Source/mastodon/t2m/ve/lib/python3.6/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/Users/fil/Source/mastodon/t2m/ve/lib/python3.6/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/Users/fil/Source/mastodon/t2m/ve/lib/python3.6/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "./t2m", line 211, in all
    db = forward(db, twitter_handle, db[twitter_handle]["mastodon"], debug, retweets=retweets)
  File "./t2m", line 86, in forward
    retweeted_status = i.quoted_status
AttributeError: 'Status' object has no attribute 'quoted_status'
```

works up until a6e1a4bce7fb1eb432baf8dfd8cbcf97accd2acc (found by git bisect)

**Comment by Psycojoker** [comment]
I think it was already fixed but that should be good now.

**Comment by Elizabithi1** [comment]
I have the same problem why it is closed without being solved?

**Comment by Psycojoker** [comment]
If you look at the linked comment it is in theory solved https://github.com/YoloSwagTeam/t2m/commit/6c94046855a9583ea0522e5d86ae3b9aedfa6d73

Are you correctly up to date? Do you have a traceback showing the error?
